package pojos;
// Generated 08.Tem.2018 19:52:39 by Hibernate Tools 4.3.1



/**
 * UserTbl generated by hbm2java
 */
public class UserTbl  implements java.io.Serializable {
     private int idUser;
     private String name;
     private String gender;
     private String address;

    public UserTbl() {
    }
	
    public UserTbl(int idUser) {
        this.idUser = idUser;
    }
    
    public UserTbl(int idUser, String name, String gender, String address) {
       this.idUser = idUser;
       this.name = name;
       this.gender = gender;
       this.address = address;
    }
   
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
}


